import type { OfficeCapability } from "./capabilitiesTypes";

export const EXCEL_CAPABILITIES: OfficeCapability[] = [
  {
    app: "excel",
    operation: "insertChart",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "applyConditionalFormatting",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "setDataValidation",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "styleTable",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "none",
  },
  {
    app: "excel",
    operation: "snapshot",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "createPivotTable",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "refreshPivotTables",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "addSlicer",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "createPowerQuery",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "inspectPowerQueries",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "managePowerQuery",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "inspectCharts",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "formatChart",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "inspectWorkbookObjects",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "manageWorkbookObject",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "manageWorksheetObjects",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "captureWorkbookTemplate",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "inspectWorkbookFormatting",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "applyWorkbookTemplate",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "inspectPrintSettings",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "configurePrint",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "exportSheetsToPdf",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "exportPdf",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "traceFormulaDependencies",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "inspectFormulaDependencies",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "repairFormulaReferences",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "convertFormulasToValues",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "inspectFormulaBackups",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "restoreFormulas",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "inspectFormulaProtection",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "manageFormulaProtection",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "exportRangeToWord",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "exportRangeToPresentation",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "excel",
    operation: "buildReportPackage",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
];
