import type { OfficeCapability } from "./capabilitiesTypes";

export const PRESENTATION_CAPABILITIES: OfficeCapability[] = [
  {
    app: "presentation",
    operation: "createPresentation",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "none",
  },
  {
    app: "presentation",
    operation: "addSlide",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "none",
  },
  {
    app: "presentation",
    operation: "addSlides",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "none",
  },
  {
    app: "presentation",
    operation: "appendSlide",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "none",
  },
  {
    app: "presentation",
    operation: "appendSlides",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "none",
  },
  {
    app: "presentation",
    operation: "addSlideContent",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "none",
  },
  {
    app: "presentation",
    operation: "applyTheme",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "deleteSlides",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "normalizeLayouts",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "insertChart",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "insertTable",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "replacePictureSlot",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "alignShapes",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "snapshot",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "inspectPresentationTheme",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "inspectSlideElements",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "inspectAnimations",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "inspectSpeakerNotes",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "applyMasterBranding",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "layoutElements",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "configureAnimations",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "configureSlideShow",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "setSpeakerNotes",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "exportHandouts",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "inspectLinkedOfficeContent",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "refreshLinkedOfficeContent",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "presentation",
    operation: "relinkLinkedOfficeContent",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
];
