import type { OfficeCapability } from "./capabilitiesTypes";

export const WORD_CAPABILITIES: OfficeCapability[] = [
  {
    app: "word",
    operation: "createDocument",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "none",
  },
  {
    app: "word",
    operation: "applyHeadingStyles",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "insertOrUpdateToc",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "styleTables",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "none",
  },
  {
    app: "word",
    operation: "insertOrReplaceImage",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "setHeaderFooter",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "none",
  },
  {
    app: "word",
    operation: "snapshot",
    preferredEngine: "openxml",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "inspectDocumentFormatting",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "formatLongDocument",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "inspectReferences",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "manageReferences",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "inspectRevisions",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "manageRevisions",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "compareDocuments",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "applyTrackedChanges",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "prepareMailMergeTemplate",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "mailMerge",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "batchMailMerge",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "inspectContentControls",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "populateContentControls",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "manageContentControls",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "exportPdf",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "inspectLinkedOfficeContent",
    preferredEngine: "com",
    writesFile: false,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "refreshLinkedOfficeContent",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
  {
    app: "word",
    operation: "relinkLinkedOfficeContent",
    preferredEngine: "com",
    writesFile: true,
    fallback: "needsCom",
  },
];
