server {
    listen 80;
    listen [::]:80;
    server_name plugin.shelelove.top;

    access_log /var/log/nginx/wenge-product.access.log;
    error_log /var/log/nginx/wenge-product.error.log;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
