import {
  wpsCreateNamedRange,
  wpsDeleteNamedRange,
  wpsGetSheetDisplay,
  wpsGetSheetFreeze,
  wpsGetSheetPageLayout,
  wpsGetSheetProtection,
  wpsGetSheetVisibility,
  wpsListNamedRanges,
  wpsProtectSheet,
  wpsSetSheetDisplay,
  wpsSetSheetFreeze,
  wpsSetSheetPageLayout,
  wpsSetSheetVisibility,
  wpsUnprotectSheet,
  wpsUpdateChart,
  wpsUpdateNamedRange,
  wpsUpdateTable,
  wpsGetTableFilter,
  wpsApplyTableFilter,
  wpsClearTableFilter,
  wpsGetTableSort,
  wpsApplyTableSort,
  wpsClearTableSort,
  wpsInspectFormulaProtection,
  wpsManageFormulaProtection,
  wpsShapeSurface,
} from "./wpsJsaUnsupported";
import {
  wpsAddChartSeries,
  wpsDeleteChartSeries,
  wpsListChartSeries,
  wpsUpdateChartAxis,
  wpsUpdateChartDataLabels,
  wpsUpdateChartSeries,
  wpsUpdateChartSeriesAxisGroup,
  wpsGetChartImage,
  wpsUpdateChartSeriesBubbleSizes,
  wpsListChartSeriesTrendlines,
  wpsAddChartSeriesTrendline,
  wpsUpdateChartSeriesTrendline,
  wpsDeleteChartSeriesTrendline,
  wpsUpdateChartSeriesValues,
  wpsUpdateChartSource,
} from "./wpsJsaChartSeriesUnsupported";
import { wpsGetRangeImage } from "./wpsJsaRangeImageUnsupported";
import {
  wpsAutofitRange,
  wpsDeleteRange,
  wpsInsertRange,
} from "./wpsJsaRangeStructureUnsupported";

/** WPS structure surface: typed unsupported for non-range chart/structure caps. */
export const wpsStructureSurface = {
  getSheetVisibility: wpsGetSheetVisibility,
  setSheetVisibility: wpsSetSheetVisibility,
  getSheetProtection: wpsGetSheetProtection,
  protectSheet: wpsProtectSheet,
  unprotectSheet: wpsUnprotectSheet,
  listNamedRanges: wpsListNamedRanges,
  createNamedRange: wpsCreateNamedRange,
  updateNamedRange: wpsUpdateNamedRange,
  deleteNamedRange: wpsDeleteNamedRange,
  updateTable: wpsUpdateTable,
  inspectFormulaProtection: wpsInspectFormulaProtection,
  manageFormulaProtection: wpsManageFormulaProtection,
  getTableFilter: wpsGetTableFilter,
  applyTableFilter: wpsApplyTableFilter,
  clearTableFilter: wpsClearTableFilter,
  getTableSort: wpsGetTableSort,
  applyTableSort: wpsApplyTableSort,
  clearTableSort: wpsClearTableSort,
  updateChart: wpsUpdateChart,
  listChartSeries: wpsListChartSeries,
  updateChartSeries: wpsUpdateChartSeries,
  deleteChartSeries: wpsDeleteChartSeries,
  addChartSeries: wpsAddChartSeries,
  updateChartSeriesValues: wpsUpdateChartSeriesValues,
  updateChartSeriesBubbleSizes: wpsUpdateChartSeriesBubbleSizes,
  listChartSeriesTrendlines: wpsListChartSeriesTrendlines,
  addChartSeriesTrendline: wpsAddChartSeriesTrendline,
  updateChartSeriesTrendline: wpsUpdateChartSeriesTrendline,
  deleteChartSeriesTrendline: wpsDeleteChartSeriesTrendline,
  getChartImage: wpsGetChartImage,
  getRangeImage: wpsGetRangeImage,
  insertRange: wpsInsertRange,
  deleteRange: wpsDeleteRange,
  autofitRange: wpsAutofitRange,
  updateChartSource: wpsUpdateChartSource,
  updateChartAxis: wpsUpdateChartAxis,
  updateChartDataLabels: wpsUpdateChartDataLabels,
  updateChartSeriesAxisGroup: wpsUpdateChartSeriesAxisGroup,
  getSheetDisplay: wpsGetSheetDisplay,
  setSheetDisplay: wpsSetSheetDisplay,
  getSheetFreeze: wpsGetSheetFreeze,
  setSheetFreeze: wpsSetSheetFreeze,
  getSheetPageLayout: wpsGetSheetPageLayout,
  setSheetPageLayout: wpsSetSheetPageLayout,
  listShapes: wpsShapeSurface.listShapes,
  createShape: wpsShapeSurface.createShape,
  deleteShape: wpsShapeSurface.deleteShape,
  updateShape: wpsShapeSurface.updateShape,
} as const;
