import {
  wpsCreateNamedRange,
  wpsDeleteNamedRange,
  wpsGetSheetDisplay,
  wpsGetSheetFreeze,
  wpsGetSheetPageLayout,
  wpsGetSheetProtection,
  wpsGetSheetVisibility,
  wpsListNamedRanges,
  wpsProtectSheet,
  wpsSetSheetDisplay,
  wpsSetSheetFreeze,
  wpsSetSheetPageLayout,
  wpsSetSheetVisibility,
  wpsUnprotectSheet,
  wpsUpdateChart,
  wpsUpdateNamedRange,
  wpsUpdateTable,
  wpsShapeSurface,
} from "./wpsJsaUnsupported";
import {
  wpsAddChartSeries,
  wpsDeleteChartSeries,
  wpsListChartSeries,
  wpsUpdateChartAxis,
  wpsUpdateChartDataLabels,
  wpsUpdateChartSeries,
  wpsUpdateChartSeriesAxisGroup,
  wpsGetChartImage,
  wpsUpdateChartSeriesBubbleSizes,
  wpsUpdateChartSeriesValues,
  wpsUpdateChartSource,
} from "./wpsJsaChartSeriesUnsupported";

/** WPS structure surface: typed unsupported for non-range chart/structure caps. */
export const wpsStructureSurface = {
  getSheetVisibility: wpsGetSheetVisibility,
  setSheetVisibility: wpsSetSheetVisibility,
  getSheetProtection: wpsGetSheetProtection,
  protectSheet: wpsProtectSheet,
  unprotectSheet: wpsUnprotectSheet,
  listNamedRanges: wpsListNamedRanges,
  createNamedRange: wpsCreateNamedRange,
  updateNamedRange: wpsUpdateNamedRange,
  deleteNamedRange: wpsDeleteNamedRange,
  updateTable: wpsUpdateTable,
  updateChart: wpsUpdateChart,
  listChartSeries: wpsListChartSeries,
  updateChartSeries: wpsUpdateChartSeries,
  deleteChartSeries: wpsDeleteChartSeries,
  addChartSeries: wpsAddChartSeries,
  updateChartSeriesValues: wpsUpdateChartSeriesValues,
  updateChartSeriesBubbleSizes: wpsUpdateChartSeriesBubbleSizes,
  getChartImage: wpsGetChartImage,
  updateChartSource: wpsUpdateChartSource,
  updateChartAxis: wpsUpdateChartAxis,
  updateChartDataLabels: wpsUpdateChartDataLabels,
  updateChartSeriesAxisGroup: wpsUpdateChartSeriesAxisGroup,
  getSheetDisplay: wpsGetSheetDisplay,
  setSheetDisplay: wpsSetSheetDisplay,
  getSheetFreeze: wpsGetSheetFreeze,
  setSheetFreeze: wpsSetSheetFreeze,
  getSheetPageLayout: wpsGetSheetPageLayout,
  setSheetPageLayout: wpsSetSheetPageLayout,
  listShapes: wpsShapeSurface.listShapes,
  createShape: wpsShapeSurface.createShape,
  deleteShape: wpsShapeSurface.deleteShape,
  updateShape: wpsShapeSurface.updateShape,
} as const;
